rtspDisable: no
protocols: [tcp]
rtspAddress: 0.0.0.0:8554

rtmpDisable: yes

hlsDisable: no
hlsAddress: 0.0.0.0:8888
hlsSegmentCount: 4
hlsSegmentDuration: 2s

api: yes
apiAddress: 127.0.0.1:55456

paths:
  all:
    fallback:
    disablePublisherOverride: no

3ce1a15e2437_stream:
  source: publisher
  runOnDemand: /usr/bin/mosquitto_pub -u $MQTTUSER -P $MQTTPASSWORD -h $MQTTHOST -p $MQTTPORT -t ring/a9ce28cb-fafb-421c-4508-29d54f48cbd3/camera/3ce1a15e2437/stream/command -m ON
  runOnDemandRestart: yes
  runOnDemandStartTimeout: 20s
  runOnDemandCloseAfter: 5s