readTimeout: 10s
readBufferCount: 8192

rtspDisable: no
protocols: [tcp, udp]
rtspAddress: 0.0.0.0:8554

rtmpDisable: yes

hlsDisable: yes

api: yes
apiAddress: 127.0.0.1:8880

paths:
  all:
    fallback:
    disablePublisherOverride: no
