readTimeout: 2s
readBufferCount: 1024

rtspDisable: no
protocols: [tcp]
rtspAddress: 0.0.0.0:8554

rtmpDisable: no
rtmpAddress: :1935

hlsDisable: no
hlsAddress: :8888
hlsAlwaysRemux: no
hlsSegmentCount: 3
hlsSegmentDuration: 1s
hlsAllowOrigin: '*'

api: yes
apiAddress: 127.0.0.1:8880

paths:
  all:
    fallback:
    disablePublisherOverride: no
