readTimeout: 1s
readBufferCount: 512

rtspDisable: no
protocols: [tcp]
rtspAddress: 0.0.0.0:8554

rtmpDisable: no
rtmpAddress: 0.0.0.0:8935

hlsDisable: yes

api: yes
apiAddress: 127.0.0.1:8443

paths:
  all:
    fallback:
    disablePublisherOverride: no
