readTimeout: 1s
readBufferCount: 128

rtspDisable: no
protocols: [udp]
rtspAddress: 0.0.0.0:8554

rtmpDisable: yes

hlsDisable: yes

api: yes
apiAddress: 127.0.0.1:8443

paths:
  all:
    fallback:
    disablePublisherOverride: no
